export type GameTeamPlayer = {
  started:        boolean,
  seconds:        number,
  fgMade:         number,
  fgAttempted:    number,
  fg3Made:        number,
  fg3Attempted:   number,
  ftMade:         number,
  ftAttempted:    number,
  points:         number,
  offRebounds:    number,
  defRebounds:    number,
  rebounds:       number,
  assists:        number,
  steals:         number,
  blocks:         number,
  turnovers:      number,
  personalFouls:  number,
  technicalFouls: number,
  gameTeamId:     number,
  teamId:         number,
  playerId:       number,
}
